<?php

return [
    'modules' => [
        'dashboard' => [
            'permission' => 'dashboard.view',
            'number' => '①',
            'title' => 'Tableau de bord',
            'subtitle' => 'Vue synthétique de votre activité comptable',
            'icon' => 'ti-dashboard',
            'color' => 'primary',
            'items' => [
                [
                    'title' => 'KPIs & trésorerie',
                    'description' => 'Indicateurs clés, flux de trésorerie et soldes bancaires en temps réel.',
                    'icon' => 'ti-chart-line',
                    'route' => 'dashboard',
                ],
                [
                    'title' => 'Soldes clés',
                    'description' => 'Synthèse des comptes principaux, caisse et banques.',
                    'icon' => 'ti-wallet',
                    'route' => 'dashboard',
                ],
                [
                    'title' => 'Alertes & relances',
                    'description' => 'Échéances, anomalies de saisie et points de vigilance.',
                    'icon' => 'ti-bell-ringing',
                    'route' => 'dashboard',
                ],
                [
                    'title' => 'Raccourcis saisie',
                    'description' => 'Accès rapide aux journaux et nouvelles écritures.',
                    'icon' => 'ti-bolt',
                    'route' => 'accounting.modules.show',
                    'params' => ['module' => 'saisie'],
                ],
            ],
        ],
        'saisie' => [
            'permission' => 'saisie.view',
            'number' => '②',
            'title' => 'Saisie comptable',
            'subtitle' => 'Journaux, import relevés, pièces jointes et devises',
            'icon' => 'ti-pencil',
            'color' => 'success',
            'items' => [
                [
                    'title' => 'Nouvelle écriture',
                    'description' => 'Saisie guidée d\'une écriture comptable multi-lignes.',
                    'icon' => 'ti-file-plus',
                    'route' => 'accounting.saisie.nouvelle',
                ],
                [
                    'title' => 'Journal des achats',
                    'description' => 'Enregistrement des factures fournisseurs et charges.',
                    'icon' => 'ti-shopping-cart',
                    'route' => 'accounting.saisie.achats',
                ],
                [
                    'title' => 'Journal des ventes',
                    'description' => 'Facturation clients et produits des ventes.',
                    'icon' => 'ti-receipt',
                    'route' => 'accounting.saisie.ventes',
                ],
                [
                    'title' => 'Journal de banque',
                    'description' => 'Mouvements bancaires, virements et chèques.',
                    'icon' => 'ti-building-bank',
                    'route' => 'accounting.saisie.banque',
                ],
                [
                    'title' => 'Journal de caisse',
                    'description' => 'Encaissements et décaissements en espèces.',
                    'icon' => 'ti-cash',
                    'route' => 'accounting.saisie.caisse',
                ],
                [
                    'title' => 'Opérations diverses',
                    'description' => 'OD, régularisations et écritures exceptionnelles.',
                    'icon' => 'ti-adjustments',
                    'route' => 'accounting.saisie.od',
                ],
                [
                    'title' => 'Import relevé bancaire',
                    'description' => 'Import CSV/OFX et rapprochement automatique.',
                    'icon' => 'ti-file-upload',
                    'route' => 'accounting.saisie.import-releve',
                ],
                [
                    'title' => 'Écritures en devises',
                    'description' => 'Saisie multi-devises avec conversion au taux du jour.',
                    'icon' => 'ti-currency-dollar',
                    'route' => 'accounting.saisie.devises',
                ],
            ],
        ],
        'livres' => [
            'permission' => 'livres.view',
            'number' => '③',
            'title' => 'Livres comptables',
            'subtitle' => 'Consultation des journaux, balances et lettrage',
            'icon' => 'ti-books',
            'color' => 'info',
            'items' => [
                [
                    'title' => 'Journal général',
                    'description' => 'Consultation chronologique de toutes les écritures.',
                    'icon' => 'ti-notebook',
                    'route' => 'accounting.livres.journal',
                ],
                [
                    'title' => 'Grand livre',
                    'description' => 'Mouvements détaillés par compte du plan SYSCOHADA.',
                    'icon' => 'ti-book-2',
                    'route' => 'accounting.livres.grand-livre',
                ],
                [
                    'title' => 'Balance générale',
                    'description' => 'Balance de vérification avec soldes débiteurs et créditeurs.',
                    'icon' => 'ti-scale',
                    'route' => 'accounting.livres.balance',
                ],
                [
                    'title' => 'Balance auxiliaire',
                    'description' => 'Balances clients, fournisseurs et comptes de tiers.',
                    'icon' => 'ti-scale-outline',
                    'route' => 'accounting.livres.auxiliaire',
                ],
                [
                    'title' => 'Lettrage des comptes',
                    'description' => 'Pointage et lettrage manuel ou automatique.',
                    'icon' => 'ti-checkup-list',
                    'route' => 'accounting.livres.lettrage',
                ],
                [
                    'title' => 'Livre de banque',
                    'description' => 'Mouvements et soldes des comptes bancaires (52x).',
                    'icon' => 'ti-building-bank',
                    'route' => 'accounting.livres.banque',
                ],
                [
                    'title' => 'Livre de caisse',
                    'description' => 'Mouvements et soldes de caisse (57x).',
                    'icon' => 'ti-cash',
                    'route' => 'accounting.livres.caisse',
                ],
                [
                    'title' => 'Rapprochement bancaire',
                    'description' => 'Rapprochement relevé bancaire / comptabilité.',
                    'icon' => 'ti-arrows-exchange',
                    'route' => 'accounting.livres.banque',
                ],
                [
                    'title' => 'Comptes de tiers',
                    'description' => 'Situation détaillée clients, fournisseurs et personnel.',
                    'icon' => 'ti-users-group',
                    'route' => 'accounting.livres.comptes-tiers',
                ],
            ],
        ],
        'etats' => [
            'permission' => 'etats.view',
            'number' => '④',
            'title' => 'États financiers',
            'subtitle' => 'États SYSCOHADA, annexes et exports',
            'icon' => 'ti-report-analytics',
            'color' => 'warning',
            'items' => [
                [
                    'title' => 'Bilan actif / passif',
                    'description' => 'Bilan fonctionnel conforme au référentiel OHADA.',
                    'icon' => 'ti-columns',
                    'route' => 'accounting.etats.bilan',
                ],
                [
                    'title' => 'Compte de résultat',
                    'description' => 'Charges, produits et résultat de l\'exercice.',
                    'icon' => 'ti-chart-bar',
                    'route' => 'accounting.etats.compte-resultat',
                ],
                [
                    'title' => 'Tableau flux trésorerie',
                    'description' => 'Mouvements de trésorerie par activité.',
                    'icon' => 'ti-arrows-shuffle',
                    'route' => 'accounting.etats.flux-tresorerie',
                ],
                [
                    'title' => 'Tableau de variation KP',
                    'description' => 'Variation des capitaux propres sur l\'exercice.',
                    'icon' => 'ti-trending-up',
                    'route' => 'accounting.etats.variation-kp',
                ],
                [
                    'title' => 'Annexes SYSCOHADA',
                    'description' => 'Notes et informations complémentaires aux états.',
                    'icon' => 'ti-file-description',
                    'route' => 'accounting.etats.annexes',
                ],
                [
                    'title' => 'Comparatif N / N-1',
                    'description' => 'Analyse comparative entre deux exercices.',
                    'icon' => 'ti-git-compare',
                    'route' => 'accounting.etats.comparatif',
                ],
                [
                    'title' => 'Export PDF / Excel',
                    'description' => 'Export des états financiers et livres comptables.',
                    'icon' => 'ti-file-export',
                    'route' => 'accounting.etats.exports',
                ],
            ],
        ],
        'facturation' => [
            'permission' => 'facturation.view',
            'number' => '⑤',
            'title' => 'Facturation & trésorerie',
            'subtitle' => 'Factures, paiements, demandes de fonds et échéanciers',
            'icon' => 'ti-file-invoice',
            'color' => 'teal',
            'items' => [
                [
                    'title' => 'Factures clients',
                    'description' => 'Création, validation et suivi des factures de vente.',
                    'icon' => 'ti-receipt',
                    'route' => 'accounting.facturation.clients',
                ],
                [
                    'title' => 'Factures fournisseurs',
                    'description' => 'Saisie et validation des factures d\'achat.',
                    'icon' => 'ti-truck-delivery',
                    'route' => 'accounting.facturation.fournisseurs',
                ],
                [
                    'title' => 'Avoirs',
                    'description' => 'Notes de crédit clients et fournisseurs.',
                    'icon' => 'ti-receipt-refund',
                    'route' => 'accounting.facturation.avoirs-clients',
                ],
                [
                    'title' => 'Paiements',
                    'description' => 'Encaissements, décaissements et reçus PDF.',
                    'icon' => 'ti-cash',
                    'route' => 'accounting.facturation.paiements',
                ],
                [
                    'title' => 'Demandes de fonds',
                    'description' => 'Workflow de validation paramétrable.',
                    'icon' => 'ti-git-pull-request',
                    'route' => 'accounting.facturation.demandes',
                ],
                [
                    'title' => 'Échéancier clients',
                    'description' => 'Créances et retards de paiement.',
                    'icon' => 'ti-calendar-due',
                    'route' => 'accounting.facturation.echeancier-clients',
                ],
                [
                    'title' => 'Échéancier fournisseurs',
                    'description' => 'Dettes et échéances à payer.',
                    'icon' => 'ti-calendar-stats',
                    'route' => 'accounting.facturation.echeancier-fournisseurs',
                ],
                [
                    'title' => 'Produits & workflow',
                    'description' => 'Catalogue produits et configuration des circuits.',
                    'icon' => 'ti-settings',
                    'route' => 'accounting.facturation.produits',
                ],
            ],
        ],
        'fiscalite' => [
            'permission' => 'fiscalite.view',
            'number' => '⑥',
            'title' => 'Fiscalité & déclarations',
            'subtitle' => 'TVA, impôts et obligations fiscales',
            'icon' => 'ti-receipt-tax',
            'color' => 'danger',
            'items' => [
                [
                    'title' => 'TVA collectée',
                    'description' => 'Suivi de la TVA facturée sur les ventes.',
                    'icon' => 'ti-percentage',
                    'route' => 'accounting.fiscalite.tva-collectee',
                ],
                [
                    'title' => 'TVA déductible',
                    'description' => 'TVA récupérable sur achats et charges.',
                    'icon' => 'ti-receipt-refund',
                    'route' => 'accounting.fiscalite.tva-deductible',
                ],
                [
                    'title' => 'DSF',
                    'description' => 'Déclaration Statistique et Fiscale annuelle.',
                    'icon' => 'ti-file-invoice',
                    'route' => 'accounting.fiscalite.dsf',
                ],
                [
                    'title' => 'Impôt sur les sociétés',
                    'description' => 'Calcul, provisions et déclarations IS.',
                    'icon' => 'ti-building',
                    'route' => 'accounting.fiscalite.is',
                ],
                [
                    'title' => 'Génération déclarations',
                    'description' => 'Préparation automatique des formulaires fiscaux.',
                    'icon' => 'ti-wand',
                    'route' => 'accounting.fiscalite.declarations',
                ],
                [
                    'title' => 'Suivi des échéances',
                    'description' => 'Calendrier fiscal et rappels de dépôt.',
                    'icon' => 'ti-calendar-due',
                    'route' => 'accounting.fiscalite.echeances',
                ],
            ],
        ],
        'exercices' => [
            'permission' => 'exercices.view',
            'number' => '⑦',
            'title' => 'Exercices comptables',
            'subtitle' => 'Ouverture, clôture et gestion multi-exercices',
            'icon' => 'ti-calendar-stats',
            'color' => 'secondary',
            'items' => [
                [
                    'title' => 'Ouverture d\'exercice',
                    'description' => 'Initialisation et bilan d\'ouverture.',
                    'icon' => 'ti-door-enter',
                    'route' => 'accounting.exercices.ouverture',
                ],
                [
                    'title' => 'Clôture comptable',
                    'description' => 'Clôture mensuelle ou annuelle de l\'exercice.',
                    'icon' => 'ti-lock',
                    'route' => 'accounting.exercices.cloture',
                ],
                [
                    'title' => 'Report à nouveau',
                    'description' => 'Reprise des soldes et à-nouveaux.',
                    'icon' => 'ti-arrow-forward-up',
                    'route' => 'accounting.exercices.report-a-nouveau',
                ],
                [
                    'title' => 'Multi-exercices',
                    'description' => 'Gestion et bascule entre plusieurs exercices.',
                    'icon' => 'ti-layers-linked',
                    'route' => 'accounting.exercices.index',
                ],
                [
                    'title' => 'Comparatif N / N-1',
                    'description' => 'Analyse inter-exercices des soldes et résultats.',
                    'icon' => 'ti-chart-dots-3',
                    'route' => 'accounting.etats.comparatif',
                ],
            ],
        ],
        'parametres' => [
            'permission' => 'parametres.view',
            'number' => '⑧',
            'title' => 'Paramètres',
            'subtitle' => 'Configuration du référentiel et de l\'organisation',
            'icon' => 'ti-settings',
            'color' => 'info',
            'items' => [
                [
                    'title' => 'Plan comptable SYSCOHADA',
                    'description' => 'Classes, comptes et sous-comptes du plan OHADA.',
                    'icon' => 'ti-list-tree',
                    'route' => 'accounting.parametres.plan-comptable',
                ],
                [
                    'title' => 'Journaux comptables',
                    'description' => 'Définition des journaux achats, ventes, banque, caisse…',
                    'icon' => 'ti-notebook',
                    'route' => 'accounting.parametres.journaux',
                ],
                [
                    'title' => 'Devises & taux de change',
                    'description' => 'Monnaies, taux journaliers et règles de conversion.',
                    'icon' => 'ti-currency-euro',
                    'route' => 'accounting.parametres.devises',
                ],
                [
                    'title' => 'Tiers (clients, fournisseurs)',
                    'description' => 'Fichier des tiers et comptes auxiliaires.',
                    'icon' => 'ti-address-book',
                    'route' => 'accounting.parametres.tiers',
                ],
                [
                    'title' => 'Utilisateurs',
                    'description' => 'Gestion des comptes et accès utilisateurs.',
                    'icon' => 'ti-users',
                    'route' => 'admin.users',
                    'permission' => 'users.view',
                ],
                [
                    'title' => 'Rôles & permissions',
                    'description' => 'Définition des rôles et droits d\'accès.',
                    'icon' => 'ti-shield-lock',
                    'route' => 'admin.roles',
                    'permission' => 'roles.view',
                ],
                [
                    'title' => 'Société & exercice',
                    'description' => 'Informations légales, devise et exercice courant.',
                    'icon' => 'ti-building-community',
                    'route' => 'accounting.parametres.societe',
                ],
                [
                    'title' => 'Sauvegardes',
                    'description' => 'Sauvegarde et restauration des données comptables.',
                    'icon' => 'ti-database-export',
                    'route' => 'accounting.placeholder',
                    'params' => ['slug' => 'sauvegardes'],
                ],
            ],
        ],
    ],
];
