<?php

/**
 * Structure des états financiers SYSCOHADA — Système normal.
 * Chaque ligne : ref, libelle, note, type (titre|ligne|formule|total), prefixes[], nature (actif|passif|produit|charge).
 */
return [
    'notes' => [
        '3' => 'Immobilisations incorporelles',
        '4' => 'Immobilisations corporelles',
        '5' => 'Immobilisations financières',
        '6' => 'Stocks et en-cours',
        '7' => 'Créances et emplois assimilés',
        '8' => 'Titres de placement et valeurs à encaisser',
        '9' => 'Trésorerie actif',
        '10' => 'Capitaux propres',
        '11' => 'Emprunts et dettes financières',
        '12' => 'Dettes circulantes',
        '13' => 'Trésorerie passif',
        '21' => 'Ventes et activités',
        '22' => 'Achats',
        '23' => 'Transports',
        '24' => 'Services extérieurs',
        '25' => 'Impôts et taxes',
        '26' => 'Autres charges',
        '27' => 'Charges de personnel',
        '28' => 'Dotations et reprises',
        '29' => 'Charges et produits financiers',
        '30' => 'HAO et participations',
    ],

    'bilan' => [
        'actif' => [
            ['type' => 'equilibre', 'ref' => 'XAP', 'libelle' => 'ACTIF - PASSIF', 'formule' => 'resultat_net'],
            ['type' => 'titre', 'ref' => 'AD', 'libelle' => 'IMMOBILISATIONS INCORPORELLES'],
            ['type' => 'ligne', 'ref' => 'AE', 'libelle' => 'Frais de développement et de prospection', 'note' => '3', 'prefixes' => ['211', '218'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AF', 'libelle' => 'Brevets, licences, logiciels, et droits similaires', 'note' => '3', 'prefixes' => ['212', '213'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AG', 'libelle' => 'Fonds commercial et droit de bail', 'note' => '3', 'prefixes' => ['214', '215'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AH', 'libelle' => 'Autres immobilisations incorporelles', 'note' => '3', 'prefixes' => ['216', '217'], 'nature' => 'actif'],
            ['type' => 'titre', 'ref' => 'AI', 'libelle' => 'IMMOBILISATIONS CORPORELLES'],
            ['type' => 'ligne', 'ref' => 'AJ', 'libelle' => 'Terrains', 'note' => '4', 'prefixes' => ['221'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AK', 'libelle' => 'Bâtiments', 'note' => '4', 'prefixes' => ['222', '223'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AL', 'libelle' => 'Aménagements, agencements et installations', 'note' => '4', 'prefixes' => ['224'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AM', 'libelle' => 'Matériel, mobilier et actifs biologiques', 'note' => '4', 'prefixes' => ['225', '226', '227', '228'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AN', 'libelle' => 'Matériel de transport', 'note' => '4', 'prefixes' => ['245', '249'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AP', 'libelle' => 'Avances et acomptes versés sur immobilisations', 'note' => '4', 'prefixes' => ['251', '252'], 'nature' => 'actif'],
            ['type' => 'titre', 'ref' => 'AQ', 'libelle' => 'IMMOBILISATIONS FINANCIÈRES'],
            ['type' => 'ligne', 'ref' => 'AR', 'libelle' => 'Titres de participation', 'note' => '5', 'prefixes' => ['261', '262'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'AS', 'libelle' => 'Autres immobilisations financières', 'note' => '5', 'prefixes' => ['27'], 'nature' => 'actif'],
            ['type' => 'total', 'ref' => 'AZ', 'libelle' => 'TOTAL ACTIF IMMOBILISÉ (I)', 'somme' => 'lignes_actif_immobilise'],
            ['type' => 'ligne', 'ref' => 'BA', 'libelle' => 'ACTIF CIRCULANT HAO', 'note' => '7', 'prefixes' => ['485', '488'], 'nature' => 'actif'],
            ['type' => 'titre', 'ref' => 'BB', 'libelle' => 'STOCKS ET ENCOURS'],
            ['type' => 'ligne', 'ref' => 'BB1', 'libelle' => 'Stocks et en-cours', 'note' => '6', 'prefixes' => ['31', '32', '33', '34', '35', '36', '37', '38'], 'nature' => 'actif'],
            ['type' => 'titre', 'ref' => 'BG', 'libelle' => 'CRÉANCES ET EMPLOIS ASSIMILÉS'],
            ['type' => 'ligne', 'ref' => 'BH', 'libelle' => 'Fournisseurs avances versées', 'note' => '7', 'prefixes' => ['409', '401'], 'nature' => 'actif', 'sens_comptes' => ['401' => 'debit'], 'fournisseurs_debit' => true],
            ['type' => 'ligne', 'ref' => 'BI', 'libelle' => 'Clients', 'note' => '7', 'prefixes' => ['41'], 'nature' => 'actif', 'exclude_prefixes' => ['419'], 'detail_comptes' => true],
            ['type' => 'ligne', 'ref' => 'BJ', 'libelle' => 'Autres créances', 'note' => '7', 'prefixes' => ['42', '43', '44', '45', '46', '47'], 'nature' => 'actif', 'exclude_prefixes' => ['409', '411', '419', '485', '488']],
            ['type' => 'total', 'ref' => 'BGT', 'libelle' => 'CRÉANCES ET EMPLOIS ASSIMILÉS', 'somme_refs' => ['BH', 'BI', 'BJ'], 'masquer_si_vide' => false],
            ['type' => 'total', 'ref' => 'BK', 'libelle' => 'TOTAL ACTIF CIRCULANT', 'somme_refs' => ['BA', 'BB1', 'BGT']],
            ['type' => 'ligne', 'ref' => 'BQ', 'libelle' => 'Titres de placement', 'note' => '8', 'prefixes' => ['50'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'BR', 'libelle' => 'Valeurs à encaisser', 'note' => '8', 'prefixes' => ['51'], 'nature' => 'actif'],
            ['type' => 'ligne', 'ref' => 'BS', 'libelle' => 'Banques, chèques postaux, caisses et assimilés', 'note' => '11', 'prefixes' => ['52', '53', '54', '55', '57', '58'], 'nature' => 'actif', 'tresorerie_signee' => true, 'detail_comptes' => true, 'exclude_prefixes' => ['59']],
            ['type' => 'total', 'ref' => 'BT', 'libelle' => 'TOTAL TRÉSORERIE-ACTIF (II)', 'somme_refs' => ['BS']],
            ['type' => 'ligne', 'ref' => 'BU', 'libelle' => 'Écarts de conversion actif (V)', 'note' => '9', 'prefixes' => ['478'], 'nature' => 'actif'],
            ['type' => 'total', 'ref' => 'BZ', 'libelle' => 'TOTAL GÉNÉRAL', 'somme_refs' => ['AZ', 'BK', 'BT', 'BU'], 'alias_ref' => 'TA'],
        ],
        'passif' => [
            ['type' => 'titre', 'ref' => 'CA', 'libelle' => 'PASSIF'],
            ['type' => 'ligne', 'ref' => 'CA1', 'libelle' => 'Capital', 'note' => '10', 'prefixes' => ['101', '102', '103'], 'nature' => 'passif', 'capital_positif' => true],
            ['type' => 'ligne', 'ref' => 'CB', 'libelle' => 'Apporteurs capital non appelé', 'note' => '10', 'prefixes' => ['109'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'CD', 'libelle' => 'Primes liées au capital social', 'note' => '10', 'prefixes' => ['104'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'CE', 'libelle' => 'Écarts de réévaluation', 'note' => '10', 'prefixes' => ['105'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'CF', 'libelle' => 'Réserves indisponibles', 'note' => '10', 'prefixes' => ['106'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'CG', 'libelle' => 'Réserves libres', 'note' => '10', 'prefixes' => ['111', '112', '113'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'CH', 'libelle' => 'Report à nouveau', 'note' => '10', 'prefixes' => ['12'], 'nature' => 'passif', 'exclude_prefixes' => ['13']],
            ['type' => 'ligne', 'ref' => 'CJ', 'libelle' => 'Résultat net de l\'exercice', 'note' => '10', 'prefixes' => ['13'], 'nature' => 'passif', 'resultat_exercice' => true],
            ['type' => 'ligne', 'ref' => 'CL', 'libelle' => 'Subventions d\'investissement', 'note' => '10', 'prefixes' => ['14'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'CM', 'libelle' => 'Provisions réglementées', 'note' => '10', 'prefixes' => ['15'], 'nature' => 'passif'],
            ['type' => 'total', 'ref' => 'CP', 'libelle' => 'TOTAL CAPITAUX PROPRES ET RESSOURCES ASSIMILÉES (I)', 'somme_refs' => ['CA1', 'CB', 'CD', 'CE', 'CF', 'CG', 'CH', 'CJ', 'CL', 'CM']],
            ['type' => 'ligne', 'ref' => 'DA', 'libelle' => 'Emprunts et dettes financières diverses', 'note' => '11', 'prefixes' => ['16', '17'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'DB', 'libelle' => 'Dettes de location-acquisition', 'note' => '11', 'prefixes' => ['18'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'DC', 'libelle' => 'Provisions financières pour risques et charges', 'note' => '11', 'prefixes' => ['19'], 'nature' => 'passif'],
            ['type' => 'total', 'ref' => 'DD', 'libelle' => 'TOTAL DETTES FINANCIERS ET RESSOURCES ASSIMILÉES (II)', 'somme_refs' => ['DA', 'DB', 'DC']],
            ['type' => 'total', 'ref' => 'DF', 'libelle' => 'TOTAL RESSOURCES STABLES (III)', 'somme_refs' => ['CP', 'DD']],
            ['type' => 'ligne', 'ref' => 'DH', 'libelle' => 'Dettes circulantes HAO', 'note' => '12', 'prefixes' => ['481', '482', '484'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'DI', 'libelle' => 'Clients, avances reçues', 'note' => '12', 'prefixes' => ['419'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'DJ', 'libelle' => 'Fournisseurs d\'exploitations', 'note' => '17', 'prefixes' => ['401'], 'nature' => 'passif', 'affichage_signe' => true, 'fournisseurs_credit' => true, 'detail_comptes' => true],
            ['type' => 'ligne', 'ref' => 'DK', 'libelle' => 'Dettes fiscales et sociales', 'note' => '12', 'prefixes' => ['43', '44'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'DM', 'libelle' => 'Autres dettes', 'note' => '12', 'prefixes' => ['45', '46', '47', '48'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'DN', 'libelle' => 'Provisions pour risques à court terme', 'note' => '12', 'prefixes' => ['49'], 'nature' => 'passif'],
            ['type' => 'total', 'ref' => 'DP', 'libelle' => 'TOTAL PASSIF CIRCULANT', 'somme_refs' => ['DH', 'DI', 'DJ', 'DK', 'DM', 'DN'], 'affichage_signe' => true],
            ['type' => 'ligne', 'ref' => 'DQ', 'libelle' => 'Banques, crédits d\'escompte et de trésorerie', 'note' => '13', 'prefixes' => ['56'], 'nature' => 'passif'],
            ['type' => 'ligne', 'ref' => 'DR', 'libelle' => 'Banques, établissements financiers et crédits de trésorerie', 'note' => '13', 'prefixes' => ['52', '53', '54', '55', '57', '58', '59'], 'nature' => 'passif', 'tresorerie_passif' => true, 'detail_comptes' => true],
            ['type' => 'total', 'ref' => 'DT', 'libelle' => 'TOTAL TRÉSORERIE PASSIF', 'somme_refs' => ['DQ', 'DR']],
            ['type' => 'ligne', 'ref' => 'DV', 'libelle' => 'Écart de conversion-passif', 'note' => '13', 'prefixes' => ['479'], 'nature' => 'passif'],
            ['type' => 'total', 'ref' => 'DZ', 'libelle' => 'TOTAL GÉNÉRAL', 'somme_refs' => ['DF', 'DP', 'DT', 'DV'], 'alias_ref' => 'TPG', 'balance_egale_actif' => true],
        ],
    ],

    'compte_resultat' => [
        ['type' => 'ligne', 'ref' => 'TA', 'libelle' => 'Ventes de marchandises', 'note' => '21', 'prefixes' => ['701', '702'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'RA', 'libelle' => 'Achats de marchandises', 'note' => '22', 'prefixes' => ['601'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RB', 'libelle' => 'Variation de stocks de marchandises', 'note' => '6', 'prefixes' => ['6031'], 'nature' => 'charge'],
        ['type' => 'formule', 'ref' => 'XA', 'libelle' => 'MARGE COMMERCIALE (TA - RA + RB)', 'formule' => 'TA-RA+RB'],
        ['type' => 'ligne', 'ref' => 'TB', 'libelle' => 'Ventes de produits fabriqués', 'note' => '21', 'prefixes' => ['702', '703'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TC', 'libelle' => 'Travaux, services vendus', 'note' => '21', 'prefixes' => ['704', '705'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TD', 'libelle' => 'Produits accessoires', 'note' => '21', 'prefixes' => ['706', '707'], 'nature' => 'produit'],
        ['type' => 'formule', 'ref' => 'XB', 'libelle' => 'CHIFFRE D\'AFFAIRES (A+B+C+D)', 'formule' => 'TA+TB+TC+TD'],
        ['type' => 'ligne', 'ref' => 'TE', 'libelle' => 'Production stockée (ou déstockage)', 'note' => '6', 'prefixes' => ['6032', '6033'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TF', 'libelle' => 'Production immobilisée', 'note' => '21', 'prefixes' => ['72'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TG', 'libelle' => 'Subventions d\'exploitation', 'note' => '21', 'prefixes' => ['71'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TH', 'libelle' => 'Autres produits', 'note' => '21', 'prefixes' => ['75'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TI', 'libelle' => 'Transferts de charges d\'exploitation', 'note' => '12', 'prefixes' => ['781'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'RC', 'libelle' => 'Achats de matières premières et fournitures', 'note' => '22', 'prefixes' => ['602'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RD', 'libelle' => 'Variation de stocks matières premières', 'note' => '6', 'prefixes' => ['6032'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RE', 'libelle' => 'Autres achats', 'note' => '22', 'prefixes' => ['604', '605', '606', '607', '608'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RF', 'libelle' => 'Variation autres approvisionnements', 'note' => '6', 'prefixes' => ['6033'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RG', 'libelle' => 'Transports', 'note' => '23', 'prefixes' => ['61'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RH', 'libelle' => 'Services extérieurs', 'note' => '24', 'prefixes' => ['62', '63'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RI', 'libelle' => 'Impôts et taxes', 'note' => '25', 'prefixes' => ['64'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RJ', 'libelle' => 'Autres charges', 'note' => '26', 'prefixes' => ['65'], 'nature' => 'charge'],
        ['type' => 'formule', 'ref' => 'XC', 'libelle' => 'VALEUR AJOUTÉE', 'formule' => 'XA+TB+TC+TD+TE+TF+TG+TH+TI-RC-RD-RE-RF-RG-RH-RI-RJ'],
        ['type' => 'ligne', 'ref' => 'RK', 'libelle' => 'Charges de personnel', 'note' => '27', 'prefixes' => ['66'], 'nature' => 'charge'],
        ['type' => 'formule', 'ref' => 'XD', 'libelle' => 'EXCÉDENT BRUT D\'EXPLOITATION (XC - RK)', 'formule' => 'XC-RK'],
        ['type' => 'ligne', 'ref' => 'TJ', 'libelle' => 'Reprises amort., provisions et dépréciations', 'note' => '28', 'prefixes' => ['781', '791'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'RL', 'libelle' => 'Dotations amort., provisions et dépréciations', 'note' => '28', 'prefixes' => ['681', '691'], 'nature' => 'charge'],
        ['type' => 'formule', 'ref' => 'XE', 'libelle' => 'RÉSULTAT D\'EXPLOITATION (XD + TJ - RL)', 'formule' => 'XD+TJ-RL'],
        ['type' => 'ligne', 'ref' => 'TK', 'libelle' => 'Revenus financiers et assimilés', 'note' => '29', 'prefixes' => ['77'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TL', 'libelle' => 'Reprises provisions financières', 'note' => '28', 'prefixes' => ['797'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TM', 'libelle' => 'Transferts charges financières', 'note' => '12', 'prefixes' => ['787'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'RM', 'libelle' => 'Frais financiers et charges assimilées', 'note' => '29', 'prefixes' => ['67'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RN', 'libelle' => 'Dotations provisions financières', 'note' => '28', 'prefixes' => ['697'], 'nature' => 'charge'],
        ['type' => 'formule', 'ref' => 'XF', 'libelle' => 'RÉSULTAT FINANCIER', 'formule' => 'TK+TL+TM-RM-RN'],
        ['type' => 'formule', 'ref' => 'XG', 'libelle' => 'RÉSULTAT DES ACTIVITÉS ORDINAIRES (XE + XF)', 'formule' => 'XE+XF'],
        ['type' => 'ligne', 'ref' => 'TN', 'libelle' => 'Produits des cessions d\'immobilisations', 'note' => '30', 'prefixes' => ['82'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'TO', 'libelle' => 'Autres produits HAO', 'note' => '30', 'prefixes' => ['83', '84'], 'nature' => 'produit'],
        ['type' => 'ligne', 'ref' => 'RO', 'libelle' => 'Valeurs comptables cessions immobilisations', 'note' => '30', 'prefixes' => ['81'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RP', 'libelle' => 'Autres charges HAO', 'note' => '30', 'prefixes' => ['83', '84'], 'nature' => 'charge'],
        ['type' => 'formule', 'ref' => 'XH', 'libelle' => 'RÉSULTAT HORS ACTIVITÉS ORDINAIRES', 'formule' => 'TN+TO-RO-RP'],
        ['type' => 'ligne', 'ref' => 'RQ', 'libelle' => 'Participation des travailleurs', 'note' => '30', 'prefixes' => ['87'], 'nature' => 'charge'],
        ['type' => 'ligne', 'ref' => 'RS', 'libelle' => 'Impôts sur le résultat', 'note' => '30', 'prefixes' => ['89'], 'nature' => 'charge'],
        ['type' => 'formule', 'ref' => 'XI', 'libelle' => 'RÉSULTAT NET', 'formule' => 'XG+XH-RQ-RS'],
    ],

    'flux_tresorerie' => [
        ['type' => 'ligne', 'ref' => 'ZA', 'libelle' => 'Trésorerie nette au 1er janvier', 'note' => '9', 'formule' => 'tresorerie_ouverture'],
        ['type' => 'titre', 'libelle' => 'Flux de trésorerie provenant des activités opérationnelles'],
        ['type' => 'ligne', 'ref' => 'FA', 'libelle' => 'Capacité d\'autofinancement globale (CAFG)', 'note' => '28', 'formule' => 'cafg'],
        ['type' => 'ligne', 'ref' => 'FB', 'libelle' => 'Actif circulant HAO', 'note' => '7', 'formule' => 'variation_actif_hao'],
        ['type' => 'ligne', 'ref' => 'FC', 'libelle' => 'Variation des stocks', 'note' => '6', 'formule' => 'variation_stocks'],
        ['type' => 'ligne', 'ref' => 'FD', 'libelle' => 'Variation des clients (411)', 'note' => '7', 'formule' => 'variation_clients'],
        ['type' => 'ligne', 'ref' => 'FE', 'libelle' => 'Variation des fournisseurs (401)', 'note' => '12', 'formule' => 'variation_fournisseurs'],
        ['type' => 'formule', 'ref' => 'BFG', 'libelle' => 'Variation du BFG opérationnel (FB+FC+FD+FE)', 'formule' => 'FB+FC+FD+FE'],
        ['type' => 'formule', 'ref' => 'ZB', 'libelle' => 'Flux de trésorerie des activités opérationnelles', 'formule' => 'FA+BFG'],
        ['type' => 'titre', 'libelle' => 'Flux de trésorerie provenant des activités d\'investissement'],
        ['type' => 'ligne', 'ref' => 'FF', 'libelle' => 'Décaissements acquisitions immo. incorporelles', 'formule' => 'decaissement_immo_incorp'],
        ['type' => 'ligne', 'ref' => 'FG', 'libelle' => 'Décaissements acquisitions immo. corporelles', 'formule' => 'decaissement_immo_corp'],
        ['type' => 'ligne', 'ref' => 'FH', 'libelle' => 'Décaissements acquisitions immo. financières', 'formule' => 'decaissement_immo_fin'],
        ['type' => 'ligne', 'ref' => 'FI', 'libelle' => 'Encaissements cessions immo. incorp. et corp.', 'formule' => 'encaissement_cession_immo'],
        ['type' => 'ligne', 'ref' => 'FJ', 'libelle' => 'Encaissements cessions immo. financières', 'formule' => 'encaissement_cession_fin'],
        ['type' => 'formule', 'ref' => 'ZC', 'libelle' => 'Flux de trésorerie des opérations d\'investissement', 'formule' => 'FF+FG+FH+FI+FJ'],
        ['type' => 'titre', 'libelle' => 'Flux de trésorerie provenant du financement par les capitaux propres'],
        ['type' => 'ligne', 'ref' => 'FK', 'libelle' => 'Augmentation de capital par apports nouveaux', 'prefixes' => ['101', '104'], 'nature' => 'flux_financement'],
        ['type' => 'ligne', 'ref' => 'FL', 'libelle' => 'Subventions d\'investissement reçues', 'prefixes' => ['14'], 'nature' => 'flux_financement'],
        ['type' => 'ligne', 'ref' => 'FM', 'libelle' => 'Prélèvements sur le capital', 'formule' => 'prelevement_capital'],
        ['type' => 'ligne', 'ref' => 'FN', 'libelle' => 'Dividendes versés', 'prefixes' => ['457'], 'nature' => 'flux_financement'],
        ['type' => 'formule', 'ref' => 'ZD', 'libelle' => 'Flux de trésorerie des capitaux propres', 'formule' => 'FK+FL+FM+FN'],
        ['type' => 'titre', 'libelle' => 'Trésorerie provenant du financement par les capitaux étrangers'],
        ['type' => 'ligne', 'ref' => 'FO', 'libelle' => 'Emprunts', 'prefixes' => ['16'], 'nature' => 'flux_financement'],
        ['type' => 'ligne', 'ref' => 'FP', 'libelle' => 'Autres dettes financières', 'prefixes' => ['17'], 'nature' => 'flux_financement'],
        ['type' => 'ligne', 'ref' => 'FQ', 'libelle' => 'Remboursements emprunts et dettes financières', 'formule' => 'remboursement_emprunts'],
        ['type' => 'formule', 'ref' => 'ZE', 'libelle' => 'Flux de trésorerie des capitaux étrangers', 'formule' => 'FO+FP+FQ'],
        ['type' => 'formule', 'ref' => 'ZF', 'libelle' => 'Flux de trésorerie des activités de financement (D+E)', 'formule' => 'ZD+ZE'],
        ['type' => 'formule', 'ref' => 'ZG', 'libelle' => 'VARIATION DE LA TRÉSORERIE NETTE (B+C+F)', 'formule' => 'ZB+ZC+ZF'],
        ['type' => 'formule', 'ref' => 'ZH', 'libelle' => 'Trésorerie nette au 31 décembre (G+A)', 'formule' => 'ZG+ZA'],
        ['type' => 'ligne', 'ref' => 'CTRL', 'libelle' => 'Contrôle : ZG − (ZH − ZA) — Δ trésorerie 521+571', 'formule' => 'controle_tresorerie'],
    ],

    'variation_kp' => [
        ['libelle' => 'Capital', 'prefixes' => ['101', '102', '103']],
        ['libelle' => 'Primes et réserves', 'prefixes' => ['104', '106', '111', '112', '113']],
        ['libelle' => 'Report à nouveau', 'prefixes' => ['12']],
        ['libelle' => 'Résultat net', 'prefixes' => ['13']],
        ['libelle' => 'Subventions d\'investissement', 'prefixes' => ['14']],
        ['libelle' => 'Provisions réglementées', 'prefixes' => ['15']],
    ],

    'annexes' => [
        ['num' => 1, 'titre' => 'Règles et méthodes comptables', 'contenu' => 'Présentation conforme au référentiel SYSCOHADA révisé (Acte uniforme OHADA).'],
        ['num' => 2, 'titre' => 'Principes comptables fondamentaux', 'contenu' => 'Continuité d\'exploitation, permanence des méthodes, prudence, intangibilité du bilan d\'ouverture.'],
        ['num' => 3, 'titre' => 'Immobilisations incorporelles', 'contenu' => 'Voir note 3 — détail des immobilisations incorporelles et amortissements.'],
        ['num' => 4, 'titre' => 'Immobilisations corporelles', 'contenu' => 'Voir note 4 — terrains, bâtiments, matériel et amortissements associés.'],
        ['num' => 5, 'titre' => 'Immobilisations financières', 'contenu' => 'Titres de participation et autres immobilisations financières.'],
        ['num' => 6, 'titre' => 'Stocks et en-cours', 'contenu' => 'Méthode d\'évaluation : coût moyen pondéré / FIFO selon politique de la société.'],
        ['num' => 7, 'titre' => 'Créances et emplois assimilés', 'contenu' => 'Ventilation clients, autres créances, dépréciations éventuelles.'],
        ['num' => 8, 'titre' => 'Titres de placement', 'contenu' => 'Valeurs mobilières de placement détenues à la clôture.'],
        ['num' => 9, 'titre' => 'Trésorerie', 'contenu' => 'Soldes bancaires, caisses et équivalents de trésorerie.'],
        ['num' => 10, 'titre' => 'Capitaux propres', 'contenu' => 'Capital social, primes, réserves, report à nouveau et résultat.'],
        ['num' => 11, 'titre' => 'Emprunts et dettes financières', 'contenu' => 'Échéancier des emprunts et dettes assimilées.'],
        ['num' => 12, 'titre' => 'Dettes circulantes', 'contenu' => 'Fournisseurs, dettes fiscales et sociales, autres dettes.'],
        ['num' => 13, 'titre' => 'Trésorerie passif', 'contenu' => 'Découverts bancaires et concours bancaires courants.'],
        ['num' => 14, 'titre' => 'Chiffre d\'affaires', 'contenu' => 'Ventilation des ventes par activité ou zone géographique si pertinent.'],
        ['num' => 15, 'titre' => 'Charges externes', 'contenu' => 'Transports, services extérieurs, impôts et taxes.'],
        ['num' => 16, 'titre' => 'Charges de personnel', 'contenu' => 'Rémunérations, charges sociales et autres avantages.'],
        ['num' => 17, 'titre' => 'Dotations et reprises', 'contenu' => 'Dotations aux amortissements, provisions et reprises.'],
        ['num' => 18, 'titre' => 'Résultat financier', 'contenu' => 'Produits et charges financières de l\'exercice.'],
        ['num' => 19, 'titre' => 'Résultat HAO', 'contenu' => 'Éléments hors activités ordinaires.'],
        ['num' => 20, 'titre' => 'Impôts sur le résultat', 'contenu' => 'Détermination de l\'impôt et impôts différés éventuels.'],
        ['num' => 21, 'titre' => 'Engagements hors bilan', 'contenu' => 'Engagements donnés, reçus et autres engagements (classe 9).'],
        ['num' => 22, 'titre' => 'Parties liées', 'contenu' => 'Transactions avec les parties liées conformément à l\'OHADA.'],
        ['num' => 23, 'titre' => 'Événements postérieurs à la clôture', 'contenu' => 'Événements survenus entre la date de clôture et la date d\'arrêté des comptes.'],
    ],
];
